# Generated by Django 5.2.3 on 2025-07-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
