# Generated by Django 5.2.3 on 2025-07-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='done_voting',
            field=models.CharField(default='UNDONE', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='submitted',
            field=models.CharField(default='NOT_SUBMITTED', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
