# Generated by Django 5.2.3 on 2025-07-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_player_vote_room_done_voting_room_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
