# Generated by Django 5.2.3 on 2025-07-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_room_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='submitted',
        ),
        migrations.AddField(
            model_name='player',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
