# Generated by Django 5.2.3 on 2025-07-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_room_done_voting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='submitted',
            field=models.CharField(default='False', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='done_voting',
            field=models.CharField(default='False', max_length=100),
        ),
    ]
