# Generated by Django 5.2.3 on 2025-07-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_player_submitted_alter_room_done_voting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['id']},
        ),
    ]
