# Generated by Django 5.2.3 on 2025-06-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(related_name='offering', to='products.students'),
        ),
    ]
