# Generated by Django 5.2.3 on 2025-06-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_courses_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='branch',
        ),
    ]
