# Generated by Django 5.2.3 on 2025-06-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_teacher_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student',
            field=models.ManyToManyField(to='products.course'),
        ),
    ]
