# Generated by Django 5.2.3 on 2025-06-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_student_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='age',
        ),
    ]
