# Generated by Django 5.2.3 on 2025-06-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_course_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentsEnrolled',
        ),
    ]
