# Generated by Django 5.2.3 on 2025-06-30 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_studentsenrolled_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='studentsenrolled',
            name='age',
        ),
        migrations.AddField(
            model_name='studentsenrolled',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.school'),
            preserve_default=False,
        ),
    ]
