# Generated by Django 5.2.3 on 2025-06-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_course_teacher_remove_studentsenrolled_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsenrolled',
            name='student',
            field=models.ManyToManyField(related_name='students', to='products.course'),
        ),
    ]
