# Generated by Django 5.2.3 on 2025-07-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_studentsenrolled_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email', 'username']},
        ),
    ]
