# Generated by Django 5.2.3 on 2025-07-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
