# Generated by Django 5.2.3 on 2025-07-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_products_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthentication',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
